services:
  mongo_db:
    image: mongo:latest
    restart: always # Restart the container if it crashes
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: '1m30s'
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - default

  service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: dev
    ports:
      - "8888:8080"
    depends_on:
      - mongo_db
    networks:
      - default

  gotenberg:
    image: gotenberg/gotenberg:8
    ports:
      - "3000:3000"
    networks:
      - default
  
  alloy:
    image: grafana/alloy:latest
    ports:
      - "12345:12345"
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - alloy_data:/var/lib/alloy/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - default

volumes:
  mongo_data:
  alloy_data:

networks:
  default:
    driver: bridge
