services:
  mongo_db:
    image: mongo:latest
    restart: always # Restart the container if it crashes
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: '1m30s'
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - default

  gotenberg:
    image: gotenberg/gotenberg:8
    ports:
      - "3000:3000"
    networks:
      - default
  
volumes:
  mongo_data:

networks:
  default:
    driver: bridge
