services:
  mongo_db:
    image: mongo:latest
    restart: always # Restart the container if it crashes
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  gotenberg:
    image: gotenberg/gotenberg:8
    ports:
      - "3000:3000"

volumes:
  mongo_data:
