sonar.organization=datdev2409
sonar.projectKey=datdev2409_lab-management-website

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-server/latest/project-administration/analysis-scope/
sonar.sources=cmd,internal,pkg
sonar.tests=tests

# Ignore test files and directories
sonar.exclusions=./test-results/**/*,./playwright-report/**/*,./node_modules/**/*,./playwright.config.js

