// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: combos.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addTestToCombo = `-- name: AddTestToCombo :exec
INSERT INTO combo_tests (combo_id, test_id, test_order)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddTestToComboParams struct {
	ComboID   uuid.UUID `json:"combo_id"`
	TestID    uuid.UUID `json:"test_id"`
	TestOrder int32     `json:"test_order"`
}

func (q *Queries) AddTestToCombo(ctx context.Context, arg AddTestToComboParams) error {
	_, err := q.db.Exec(ctx, addTestToCombo, arg.ComboID, arg.TestID, arg.TestOrder)
	return err
}

const countCombosByName = `-- name: CountCombosByName :one
SELECT COUNT(*) FROM combos WHERE $1 = '' OR name ILIKE '%' || $1 || '%'
`

func (q *Queries) CountCombosByName(ctx context.Context, keyword interface{}) (int64, error) {
	row := q.db.QueryRow(ctx, countCombosByName, keyword)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCombo = `-- name: CreateCombo :one
INSERT INTO combos (name, created_at, updated_at)
VALUES ($1, NOW(), NOW())
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateCombo(ctx context.Context, name string) (Combo, error) {
	row := q.db.QueryRow(ctx, createCombo, name)
	var i Combo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComboByID = `-- name: DeleteComboByID :exec
DELETE FROM combos WHERE id = $1
`

func (q *Queries) DeleteComboByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteComboByID, id)
	return err
}

const getComboByID = `-- name: GetComboByID :one
SELECT id, name, created_at, updated_at FROM combos WHERE id = $1
`

func (q *Queries) GetComboByID(ctx context.Context, id uuid.UUID) (Combo, error) {
	row := q.db.QueryRow(ctx, getComboByID, id)
	var i Combo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getComboByIDWithTests = `-- name: GetComboByIDWithTests :one
SELECT c.id, c.name, c.created_at, c.updated_at
FROM combos c
WHERE c.id = $1
`

func (q *Queries) GetComboByIDWithTests(ctx context.Context, id uuid.UUID) (Combo, error) {
	row := q.db.QueryRow(ctx, getComboByIDWithTests, id)
	var i Combo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getComboTestCount = `-- name: GetComboTestCount :one
SELECT COUNT(*) FROM combo_tests WHERE combo_id = $1
`

func (q *Queries) GetComboTestCount(ctx context.Context, comboID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getComboTestCount, comboID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getComboTests = `-- name: GetComboTests :many
SELECT t.id, t.name, t.price, t.imported_price, t.normal_value, t.unit, t.lower_bound, t.upper_bound, t.created_at, t.updated_at
FROM tests t
INNER JOIN combo_tests ct ON t.id = ct.test_id
WHERE ct.combo_id = $1
ORDER BY ct.test_order ASC, t.name ASC
`

func (q *Queries) GetComboTests(ctx context.Context, comboID uuid.UUID) ([]Test, error) {
	rows, err := q.db.Query(ctx, getComboTests, comboID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Test
	for rows.Next() {
		var i Test
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.ImportedPrice,
			&i.NormalValue,
			&i.Unit,
			&i.LowerBound,
			&i.UpperBound,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isComboNameExists = `-- name: IsComboNameExists :one
SELECT EXISTS (SELECT 1 FROM combos WHERE name = $1 LIMIT 1)
`

func (q *Queries) IsComboNameExists(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, isComboNameExists, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAllCombos = `-- name: ListAllCombos :many
SELECT id, name, created_at, updated_at FROM combos ORDER BY name ASC
`

func (q *Queries) ListAllCombos(ctx context.Context) ([]Combo, error) {
	rows, err := q.db.Query(ctx, listAllCombos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Combo
	for rows.Next() {
		var i Combo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllTestsFromCombo = `-- name: RemoveAllTestsFromCombo :exec
DELETE FROM combo_tests WHERE combo_id = $1
`

func (q *Queries) RemoveAllTestsFromCombo(ctx context.Context, comboID uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeAllTestsFromCombo, comboID)
	return err
}

const removeTestFromCombo = `-- name: RemoveTestFromCombo :exec
DELETE FROM combo_tests WHERE combo_id = $1 AND test_id = $2
`

type RemoveTestFromComboParams struct {
	ComboID uuid.UUID `json:"combo_id"`
	TestID  uuid.UUID `json:"test_id"`
}

func (q *Queries) RemoveTestFromCombo(ctx context.Context, arg RemoveTestFromComboParams) error {
	_, err := q.db.Exec(ctx, removeTestFromCombo, arg.ComboID, arg.TestID)
	return err
}

const searchCombosByName = `-- name: SearchCombosByName :many
SELECT id, name, created_at, updated_at FROM combos WHERE $1 = '' OR name ILIKE '%' || $1 || '%' ORDER BY name ASC LIMIT $3 OFFSET $2
`

type SearchCombosByNameParams struct {
	Keyword   interface{} `json:"keyword"`
	OffsetArg int32       `json:"offset_arg"`
	LimitArg  int32       `json:"limit_arg"`
}

func (q *Queries) SearchCombosByName(ctx context.Context, arg SearchCombosByNameParams) ([]Combo, error) {
	rows, err := q.db.Query(ctx, searchCombosByName, arg.Keyword, arg.OffsetArg, arg.LimitArg)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Combo
	for rows.Next() {
		var i Combo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComboByID = `-- name: UpdateComboByID :one
UPDATE combos
SET name = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, created_at, updated_at
`

type UpdateComboByIDParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateComboByID(ctx context.Context, arg UpdateComboByIDParams) (Combo, error) {
	row := q.db.QueryRow(ctx, updateComboByID, arg.ID, arg.Name)
	var i Combo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
