// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: doctors.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countDoctorsByNameOrPhone = `-- name: CountDoctorsByNameOrPhone :one
SELECT COUNT(*) FROM doctors 
WHERE $1 = '' OR name ILIKE $1 OR phone ILIKE $1
`

func (q *Queries) CountDoctorsByNameOrPhone(ctx context.Context, keyword interface{}) (int64, error) {
	row := q.db.QueryRow(ctx, countDoctorsByNameOrPhone, keyword)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDoctor = `-- name: CreateDoctor :one
INSERT INTO doctors (name, phone, address, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
RETURNING id, name, phone, address, created_at, updated_at
`

type CreateDoctorParams struct {
	Name    string `json:"name"`
	Phone   string `json:"phone"`
	Address string `json:"address"`
}

func (q *Queries) CreateDoctor(ctx context.Context, arg CreateDoctorParams) (Doctor, error) {
	row := q.db.QueryRow(ctx, createDoctor, arg.Name, arg.Phone, arg.Address)
	var i Doctor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDoctorByID = `-- name: DeleteDoctorByID :exec
DELETE FROM doctors WHERE id = $1
`

func (q *Queries) DeleteDoctorByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDoctorByID, id)
	return err
}

const getDoctorByID = `-- name: GetDoctorByID :one
SELECT id, name, phone, address, created_at, updated_at FROM doctors WHERE id = $1
`

func (q *Queries) GetDoctorByID(ctx context.Context, id uuid.UUID) (Doctor, error) {
	row := q.db.QueryRow(ctx, getDoctorByID, id)
	var i Doctor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isDoctorNameAndPhoneExists = `-- name: IsDoctorNameAndPhoneExists :one
SELECT EXISTS (
    SELECT 1 FROM doctors 
    WHERE name = $1 AND phone = $2 
    LIMIT 1
)
`

type IsDoctorNameAndPhoneExistsParams struct {
	Name  string `json:"name"`
	Phone string `json:"phone"`
}

func (q *Queries) IsDoctorNameAndPhoneExists(ctx context.Context, arg IsDoctorNameAndPhoneExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, isDoctorNameAndPhoneExists, arg.Name, arg.Phone)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const searchDoctorsByNameOrPhone = `-- name: SearchDoctorsByNameOrPhone :many
SELECT id, name, phone, address, created_at, updated_at FROM doctors 
WHERE $1 = '' OR name ILIKE $1 OR phone ILIKE $1 
ORDER BY created_at DESC 
LIMIT $3 OFFSET $2
`

type SearchDoctorsByNameOrPhoneParams struct {
	Keyword   interface{} `json:"keyword"`
	OffsetArg int32       `json:"offset_arg"`
	LimitArg  int32       `json:"limit_arg"`
}

func (q *Queries) SearchDoctorsByNameOrPhone(ctx context.Context, arg SearchDoctorsByNameOrPhoneParams) ([]Doctor, error) {
	rows, err := q.db.Query(ctx, searchDoctorsByNameOrPhone, arg.Keyword, arg.OffsetArg, arg.LimitArg)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Doctor
	for rows.Next() {
		var i Doctor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDoctorByID = `-- name: UpdateDoctorByID :exec
UPDATE doctors
SET name = $2, phone = $3, address = $4, updated_at = NOW()
WHERE id = $1
`

type UpdateDoctorByIDParams struct {
	ID      uuid.UUID `json:"id"`
	Name    string    `json:"name"`
	Phone   string    `json:"phone"`
	Address string    `json:"address"`
}

func (q *Queries) UpdateDoctorByID(ctx context.Context, arg UpdateDoctorByIDParams) error {
	_, err := q.db.Exec(ctx, updateDoctorByID,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.Address,
	)
	return err
}
