// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Patient struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Yob       string    `json:"yob"`
	Gender    string    `json:"gender"`
	Address   string    `json:"address"`
	Phone     string    `json:"phone"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
