// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Combo struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ComboTest struct {
	ComboID   uuid.UUID `json:"combo_id"`
	TestID    uuid.UUID `json:"test_id"`
	TestOrder int32     `json:"test_order"`
}

type Doctor struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Phone     string    `json:"phone"`
	Address   string    `json:"address"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Patient struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Yob       string    `json:"yob"`
	Gender    string    `json:"gender"`
	Address   string    `json:"address"`
	Phone     string    `json:"phone"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Test struct {
	ID            uuid.UUID     `json:"id"`
	Name          string        `json:"name"`
	Price         int32         `json:"price"`
	ImportedPrice int32         `json:"imported_price"`
	NormalValue   string        `json:"normal_value"`
	Unit          string        `json:"unit"`
	LowerBound    pgtype.Float8 `json:"lower_bound"`
	UpperBound    pgtype.Float8 `json:"upper_bound"`
	CreatedAt     time.Time     `json:"created_at"`
	UpdatedAt     time.Time     `json:"updated_at"`
}
