// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: patients.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countPatientsByNameOrPhone = `-- name: CountPatientsByNameOrPhone :one
SELECT COUNT(*) FROM patients WHERE $1 = '' OR name ILIKE $1 OR phone ILIKE $1
`

func (q *Queries) CountPatientsByNameOrPhone(ctx context.Context, keyword interface{}) (int64, error) {
	row := q.db.QueryRow(ctx, countPatientsByNameOrPhone, keyword)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPatient = `-- name: CreatePatient :one
INSERT INTO patients (name, yob, gender, address, phone, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
RETURNING id, name, yob, gender, address, phone, created_at, updated_at
`

type CreatePatientParams struct {
	Name    string `json:"name"`
	Yob     string `json:"yob"`
	Gender  string `json:"gender"`
	Address string `json:"address"`
	Phone   string `json:"phone"`
}

func (q *Queries) CreatePatient(ctx context.Context, arg CreatePatientParams) (Patient, error) {
	row := q.db.QueryRow(ctx, createPatient,
		arg.Name,
		arg.Yob,
		arg.Gender,
		arg.Address,
		arg.Phone,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Yob,
		&i.Gender,
		&i.Address,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePatientByID = `-- name: DeletePatientByID :exec
DELETE FROM patients WHERE id = $1
`

func (q *Queries) DeletePatientByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePatientByID, id)
	return err
}

const getPatientByID = `-- name: GetPatientByID :one
SELECT id, name, yob, gender, address, phone, created_at, updated_at FROM patients WHERE id = $1
`

func (q *Queries) GetPatientByID(ctx context.Context, id uuid.UUID) (Patient, error) {
	row := q.db.QueryRow(ctx, getPatientByID, id)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Yob,
		&i.Gender,
		&i.Address,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isPatientNameAndPhoneExists = `-- name: IsPatientNameAndPhoneExists :one
SELECT EXISTS (SELECT 1 FROM patients WHERE name = $1 AND phone = $2 LIMIT 1)
`

type IsPatientNameAndPhoneExistsParams struct {
	Name  string `json:"name"`
	Phone string `json:"phone"`
}

func (q *Queries) IsPatientNameAndPhoneExists(ctx context.Context, arg IsPatientNameAndPhoneExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, isPatientNameAndPhoneExists, arg.Name, arg.Phone)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listPatients = `-- name: ListPatients :many
SELECT id, name, yob, gender, address, phone, created_at, updated_at FROM patients ORDER BY created_at DESC
`

func (q *Queries) ListPatients(ctx context.Context) ([]Patient, error) {
	rows, err := q.db.Query(ctx, listPatients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Patient
	for rows.Next() {
		var i Patient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Yob,
			&i.Gender,
			&i.Address,
			&i.Phone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPatientsByNameOrPhone = `-- name: SearchPatientsByNameOrPhone :many
SELECT id, name, yob, gender, address, phone, created_at, updated_at FROM patients WHERE $1 = '' OR name ILIKE '%@keyword%' OR phone ILIKE '%@keyword%' ORDER BY created_at DESC LIMIT $3 OFFSET $2
`

type SearchPatientsByNameOrPhoneParams struct {
	Keyword   interface{} `json:"keyword"`
	OffsetArg int32       `json:"offset_arg"`
	LimitArg  int32       `json:"limit_arg"`
}

func (q *Queries) SearchPatientsByNameOrPhone(ctx context.Context, arg SearchPatientsByNameOrPhoneParams) ([]Patient, error) {
	rows, err := q.db.Query(ctx, searchPatientsByNameOrPhone, arg.Keyword, arg.OffsetArg, arg.LimitArg)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Patient
	for rows.Next() {
		var i Patient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Yob,
			&i.Gender,
			&i.Address,
			&i.Phone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePatientByID = `-- name: UpdatePatientByID :exec
UPDATE patients
SET name = $2, yob = $3, address = $4, phone = $5, updated_at = NOW()
WHERE id = $1
`

type UpdatePatientByIDParams struct {
	ID      uuid.UUID `json:"id"`
	Name    string    `json:"name"`
	Yob     string    `json:"yob"`
	Address string    `json:"address"`
	Phone   string    `json:"phone"`
}

func (q *Queries) UpdatePatientByID(ctx context.Context, arg UpdatePatientByIDParams) error {
	_, err := q.db.Exec(ctx, updatePatientByID,
		arg.ID,
		arg.Name,
		arg.Yob,
		arg.Address,
		arg.Phone,
	)
	return err
}
