// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountPatientsByNameOrPhone(ctx context.Context, keyword interface{}) (int64, error)
	CreatePatient(ctx context.Context, arg CreatePatientParams) (Patient, error)
	DeletePatientByID(ctx context.Context, id uuid.UUID) error
	GetPatientByID(ctx context.Context, id uuid.UUID) (Patient, error)
	IsPatientNameAndPhoneExists(ctx context.Context, arg IsPatientNameAndPhoneExistsParams) (bool, error)
	ListPatients(ctx context.Context) ([]Patient, error)
	SearchPatientsByNameOrPhone(ctx context.Context, arg SearchPatientsByNameOrPhoneParams) ([]Patient, error)
	UpdatePatientByID(ctx context.Context, arg UpdatePatientByIDParams) error
}

var _ Querier = (*Queries)(nil)
