// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tests.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTestsByName = `-- name: CountTestsByName :one
SELECT COUNT(*) FROM tests WHERE $1 = '' OR name ILIKE '%' || $1 || '%'
`

func (q *Queries) CountTestsByName(ctx context.Context, keyword interface{}) (int64, error) {
	row := q.db.QueryRow(ctx, countTestsByName, keyword)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTest = `-- name: CreateTest :one
INSERT INTO tests (name, price, imported_price, normal_value, unit, lower_bound, upper_bound, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW(), NOW())
RETURNING id, name, price, imported_price, normal_value, unit, lower_bound, upper_bound, created_at, updated_at
`

type CreateTestParams struct {
	Name          string        `json:"name"`
	Price         int32         `json:"price"`
	ImportedPrice int32         `json:"imported_price"`
	NormalValue   string        `json:"normal_value"`
	Unit          string        `json:"unit"`
	LowerBound    pgtype.Float8 `json:"lower_bound"`
	UpperBound    pgtype.Float8 `json:"upper_bound"`
}

func (q *Queries) CreateTest(ctx context.Context, arg CreateTestParams) (Test, error) {
	row := q.db.QueryRow(ctx, createTest,
		arg.Name,
		arg.Price,
		arg.ImportedPrice,
		arg.NormalValue,
		arg.Unit,
		arg.LowerBound,
		arg.UpperBound,
	)
	var i Test
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.ImportedPrice,
		&i.NormalValue,
		&i.Unit,
		&i.LowerBound,
		&i.UpperBound,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTestByID = `-- name: DeleteTestByID :exec
DELETE FROM tests WHERE id = $1
`

func (q *Queries) DeleteTestByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTestByID, id)
	return err
}

const getTestByID = `-- name: GetTestByID :one
SELECT id, name, price, imported_price, normal_value, unit, lower_bound, upper_bound, created_at, updated_at FROM tests WHERE id = $1
`

func (q *Queries) GetTestByID(ctx context.Context, id uuid.UUID) (Test, error) {
	row := q.db.QueryRow(ctx, getTestByID, id)
	var i Test
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.ImportedPrice,
		&i.NormalValue,
		&i.Unit,
		&i.LowerBound,
		&i.UpperBound,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isTestNameExists = `-- name: IsTestNameExists :one
SELECT EXISTS (SELECT 1 FROM tests WHERE name = $1 LIMIT 1)
`

func (q *Queries) IsTestNameExists(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, isTestNameExists, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAllTests = `-- name: ListAllTests :many
SELECT id, name, price, imported_price, normal_value, unit, lower_bound, upper_bound, created_at, updated_at FROM tests ORDER BY name ASC
`

func (q *Queries) ListAllTests(ctx context.Context) ([]Test, error) {
	rows, err := q.db.Query(ctx, listAllTests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Test
	for rows.Next() {
		var i Test
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.ImportedPrice,
			&i.NormalValue,
			&i.Unit,
			&i.LowerBound,
			&i.UpperBound,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTestsByName = `-- name: SearchTestsByName :many
SELECT id, name, price, imported_price, normal_value, unit, lower_bound, upper_bound, created_at, updated_at FROM tests WHERE $1 = '' OR name ILIKE '%' || $1 || '%' ORDER BY name ASC LIMIT $3 OFFSET $2
`

type SearchTestsByNameParams struct {
	Keyword   interface{} `json:"keyword"`
	OffsetArg int32       `json:"offset_arg"`
	LimitArg  int32       `json:"limit_arg"`
}

func (q *Queries) SearchTestsByName(ctx context.Context, arg SearchTestsByNameParams) ([]Test, error) {
	rows, err := q.db.Query(ctx, searchTestsByName, arg.Keyword, arg.OffsetArg, arg.LimitArg)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Test
	for rows.Next() {
		var i Test
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.ImportedPrice,
			&i.NormalValue,
			&i.Unit,
			&i.LowerBound,
			&i.UpperBound,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTestByID = `-- name: UpdateTestByID :one
UPDATE tests
SET name = $2, price = $3, imported_price = $4, normal_value = $5, unit = $6, lower_bound = $7, upper_bound = $8, updated_at = NOW()
WHERE id = $1
RETURNING id, name, price, imported_price, normal_value, unit, lower_bound, upper_bound, created_at, updated_at
`

type UpdateTestByIDParams struct {
	ID            uuid.UUID     `json:"id"`
	Name          string        `json:"name"`
	Price         int32         `json:"price"`
	ImportedPrice int32         `json:"imported_price"`
	NormalValue   string        `json:"normal_value"`
	Unit          string        `json:"unit"`
	LowerBound    pgtype.Float8 `json:"lower_bound"`
	UpperBound    pgtype.Float8 `json:"upper_bound"`
}

func (q *Queries) UpdateTestByID(ctx context.Context, arg UpdateTestByIDParams) (Test, error) {
	row := q.db.QueryRow(ctx, updateTestByID,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.ImportedPrice,
		arg.NormalValue,
		arg.Unit,
		arg.LowerBound,
		arg.UpperBound,
	)
	var i Test
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.ImportedPrice,
		&i.NormalValue,
		&i.Unit,
		&i.LowerBound,
		&i.UpperBound,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
