api:
  insecure: true
  dashboard: true

accessLog:
  format: json

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

providers:
  docker: {}

certificatesResolvers:
  cloudflare:
    acme:
      email: datdev2409@gmail.com
      storage: /var/traefik/certs/cloudflare-acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
      keyType: EC256
      httpChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
