services:


  lab-admin-go:
    image: ${DOCKER_USERNAME:-congdat2409}/lab-admin-go:${DOCKER_TAG:-latest}
    restart: unless-stopped
    environment:
      - SERVER_PORT=9000
    labels:
      - traefik.enable=true
      - traefik.http.routers.lab-admin-http.rule=Host(`${ENV:-stg}-lab.datnguyen2409.tech`)
      - traefik.http.services.lab-admin-http.loadbalancer.server.port=9000
      - traefik.http.routers.lab-admin-https.tts=true
      - traefik.http.routers.lab-admin-https.tls.certresolver=cloudflare
      - traefik.http.routers.lab-admin-https.entrypoints=websecure
      - traefik.http.routers.lab-admin-https.rule=Host(`${ENV:-stg}-lab.datnguyen2409.tech`)
    env_file:
      - ../.env
    ports:
      - "9000:9000"
