services:
  lab-admin-go:
    image: congdat2409/lab-admin-go:2df5dea6c0a1e5be66e5ec87dd99546492598f8e
    restart: unless-stopped
    environment:
      - SERVER_PORT=9000
    labels:
      - traefik.enable=true
      - traefik.http.services.lab-admin-go.loadbalancer.server.port=9000
      - traefik.http.routers.lab-admin-go.entrypoints=web
